### ISSUE TITLE
Reword job start email to clarify

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-workflows#147]
The email text for started jobs includes the following:

> You will receive another email if the job fails or in the event of an error

https://github.com/Duke-GCB/bespin-api/blob/56505fe12615c1b99bc5193974c903073a21ee22/fixtures/emailtemplates.yaml#L4-L5

Should be:

> You will receive another email when the job completes or in the event of an error.

**Comment by johnbradley** [comment]
Fixed by #149
