### ISSUE TITLE
importing workflow requires nodejs

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin-workflows#154]
When trying to import a workflow into the dev instance had this error:
```
ERROR:data.importers:Unable to import workflow
 Traceback (most recent call last):
   File "/app/data/importers.py", line 310, in _load
    wf_importer.run()
   File "/app/data/importers.py", line 265, in run
     self._create_models()
   File "/app/data/importers.py", line 235, in _create_models
     workflow_name = self.cwl_document.get('label')
   File "/app/data/importers.py", line 78, in get
     return self.parsed.tool.get(key)
   File "/app/data/importers.py", line 61, in parsed
     self._parsed = load_tool(self.url + '#main', defaultMakeTool)
...
JavascriptException: cwltool requires Node.js engine to evaluate and 
validate Javascript expressions, but couldn't find it.  
Tried nodejs, node, docker run node:slim
```

**Comment by dleehr** [comment]
One thing I notice is that this is happening in `defaultMakeTool()`, which I believe no longer exists in the current cwltool. So let's check what code changes are needed to use the latest cwltool, and see if this dependency on nodejs still exists for parsing a workflow.

If that's not straightforward, we can add nodejs as a dependency here, but look towards refactoring this out to an external service or using the schema-salad generated classes in https://github.com/dleehr/cwlpy
