### ISSUE TITLE
Bespin shared an output project 27 times

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-workflows#177]
Logs from bespin-api [bespin-api repeated share logs.txt](https://github.com/Duke-GCB/bespin-api/files/2616051/bespin-api.repeated.share.logs.txt) attached. Some notes:

During the job, I set the `cleanup_vm` field to False, as I wanted to use this VM for testing REANA uploads.

Bespin-mailer only sent one set of notification messages, but I got 27 copies of 

```
Subject: Data ready for 'Bespin WES GATK4 Preprocessing v6 GATK4 preprocessing with haplotypecaller v5 2018-11-21'

Hello Dan Leehr,


Results are ready for your review.

Duke Data Service Project: Bespin WES GATK4 Preprocessing v6 GATK4 preprocessing with haplotypecaller v5 2018-11-21
URL: https://dataservice.duke.edu/#/project/9058e2a9-2b87-45b2-a5f0-b58a744b7fb6

Bespin job results.

Regards,

Bespin
Duke Center for Genomic and Computational Biology
```

The service that sent the emails was D4S2, but it looks like the root cause was in bespin-api or lando.

**Comment by johnbradley** [comment]
I think this was due to VM lando worker processing the `store_job_output` message multiple times.
If you look at https://datadelivery.genome.duke.edu/admin/d4s2_api/share/66/history/ you can see the share was sent multiple times. Perhaps lando server is posting this message multiple times.
