### ISSUE TITLE
Migrations from PR#194 emptying jobs table

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin-workflows#196]
After running the migrations on the dev server there were no jobs.
Fix migrations from #194 so the jobs are maintained.

**Comment by johnbradley** [comment]
I have been unable to reproduce this locally.
I added code to the migration tests to verify jobs persisted after running migrations and didn't see this issue. I also tried restoring the database backup locally and running migrations, this also worked fine.

**Comment by johnbradley** [comment]
I ran django`sqlmigrate` command an looked through the SQL created by these migrations.
I didn't see anything that should have caused this.
I am assuming the root cause was a user command line error related to backing up the dev database.
I will backup the prod database and run these migrations and will close this issue once that is succesful.

**Comment by johnbradley** [comment]
I tested these migrations against a backup of the prod database and all jobs remained.

**Comment by dleehr** [comment]
Fair to close then?

**Comment by johnbradley** [comment]
> Fair to close then?

Yep.
