### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-workflows#2]
Ever since creating the repo for our workflow documents (bespin-cwl) I find myself confusing these two repos. Any thoughts/objection/support on renaming this repo to **bespin-api**?

**Comment by johnbradley** [comment]
I like __bespin-api__ much better.

**Comment by dleehr** [comment]
bespin-api it is then.

**Comment by dleehr** [comment]
Renamed on GitHub and updated README  in 7099a4bfc7e9baf133ea179336aff4ee130ee9cb
