### ISSUE TITLE
Support for un-packed workflows

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin-workflows#204]
Currently all jobs require a url to a packed workflow. CWL packed workflows are large JSON files that are very difficult to read. Instead we would like to use an archive of a directory containing a cwl workflow. This zip file will need to be downloaded and extracted before running the workflow. With this change we will need a method to specify what file in the archive is the workflow to run.

**Comment by dleehr** [comment]
add a BooleanField to WorkflowVersion (and serializers) `packed` and it will be True for existing workflows.

**Comment by dleehr** [comment]
instead of a boolean, have a WorkflowFormat, where those types could be packed-cwl, zipped, tar, git, etc.
