### ISSUE TITLE
Unable to create a job through the API

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-workflows#6]
For API clients to create a job, they will need to specify a `workflow_version` and an `output_dir`, but these fields are read-only in the `JobSerializer`: https://github.com/Duke-GCB/bespin-api/blob/eb23233f785365cb16672933011eed3fd90ac0ac/data/serializers.py#L24

**Comment by dleehr** [comment]
I see now that the output_dir is a OneToOneField FROM the JobOutputDir model, so that would be created after the job - but we'd still need to specify the workflow when creating the job through the API

**Comment by johnbradley** [comment]
This should be fixed by pull request #11.
setup_job.sh demonstrates setting up a dummy job.
