### ISSUE TITLE
Clarify content of DDSUser.name

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-workflows#63]
In the DDSUser model, there is a name CharField with length 255.

https://github.com/Duke-GCB/bespin-api/blob/master/data/models.py#L41

Is this intended to contain a person's full name, a short username, or a username@domain.tld?

**Comment by johnbradley** [comment]
I assumed full name, but that's not a requirement. This field isn't used anywhere in the software that I am aware of. It is just to make the admin interface easier to use since the `dds_id`is a uuid.
