### ISSUE TITLE
CSRF Errors when using DRF API browser

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-workflows#68]
In attempting to debug a failed job, I logged into the API browser as an admin user. On trying to POST to /jobs/:id/restart, the system did not accept my request because of a failed CSRF token.

**Comment by johnbradley** [comment]
I was able to reproduce this on the dev website with a sample job. I can start the job via bespin-ui but not from the Browsable API interface. Running bespin-api locally (without apache) I do not see this problem.

**Comment by dleehr** [comment]
I think it's because the browsable interface is using SessionAuthentication

> When you are using SessionAuthentication, you are using Django's authentication which usually requires CSRF to be checked. Django REST Framework enforces this, only for SessionAuthentication, so you must pass the CSRF token in the X-CSRFToken header.

https://stackoverflow.com/a/26639895

Edit: bespin-ui is using TokenAuthentication, which would not be subject to the CSRF validation

**Comment by dleehr** [comment]
But as for why it would work without apache, either apache is suppressing that header, or the prod settings are

**Comment by johnbradley** [comment]
The apache config looks like it is passing auth through.
https://github.com/Duke-GCB/bespin-webapp-docker/blob/6e812f0d488330c9f929516ae3ce7fe588c9a3ef/bespin-web/bespin-web.conf#L64

**Comment by johnbradley** [comment]
There may be a problem with the OAuth code not setting a cookie or something along those lines that happens when you use the django login page.

**Comment by dleehr** [comment]
Nah, it's not OAuth - this is entirely on the DRF and django side.

1. visit https://bespin-dev.gcb.duke.edu/api/job-file-stage-groups/
2. Open developer tools, network tab
3. Click `POST` (It doesn't matter that the payload is `{}`)
4. Looking at request headers for the failed request, it shows

```
X-CSRFTOKEN:null
```

This is the header that django's SessionAuthentication needs to read, and the browser is not sending it.

Jumping into the JS source code of the browsable API real quick, it looks like the JS code needs to read the CSRF token out of the cookie data to put it in the header. Since we have the CSRF cookie set to http-only in prod, that's probably causing the failure https://github.com/Duke-GCB/bespin-api/blob/e8d7dfca20f8b3777a05ace0462ba7b9dd20fb56/bespin/settings_prod.py#L50

According to the docs for [CSRF_COOKIE_HTTPONLY](https://docs.djangoproject.com/en/1.11/ref/settings/#csrf-cookie-httponly), setting this to True isn't terribly helpful anyways:

> Designating the CSRF cookie as HttpOnly doesn’t offer any practical protection because CSRF is only to protect against cross-domain attacks. If an attacker can read the cookie via JavaScript, they’re already on the same domain as far as the browser knows, so they can do anything they like anyway. (XSS is a much bigger hole than CSRF.)

If you set the CSRF_COOKIE_HTTPONLY to true in the local dev server, does this fail?

**Comment by johnbradley** [comment]
Yes. Turning this flag on you can see this bug(reproduced using an incognito browser tab).

**Comment by johnbradley** [comment]
https://github.com/encode/django-rest-framework/pull/3854#issuecomment-256893795
